### ISSUE TITLE
Document the maximum file size for the file resource

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-block#15]
@audax commented on [Thu Jan 21 2016](https://github.com/Qabel/qabel-accounting/issues/33)

Currently the file size is set by the Tornado default max body size.

**Comment by jmt85** [comment]
?

**Comment by audax** [comment]
I moved the issue to this repo because the accounting server does not define the maximum file size anymore.

**Comment by enkore** [comment]
Isn't this already done?

Fine print from the README:

```
...
  --max-body-size                  Maximum size for uploads (default
                                   2147483648)
...
```
