### ISSUE TITLE
Support If-Modified-Since 

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-block#3]
See https://github.com/Qabel/qabel-accounting/issues/34 for the old requirement to support HEAD requests.

**Comment by julianseeger** [comment]
Additionally, we need `Last-Modified` on GET responses to use those times in the successive GETs with `If-Modified-Since`

**Comment by audax** [comment]
Implemented support for ETags with If-Not-Match (no support for If-Match!) instead.
