### ISSUE TITLE
Use moto to mock AWS/S3 for running most unit tests

### ISSUE THREAD

**Issue by enkore** [Qabel/qabel-block#34]
Avoids dependency on AWS credentials + internet for running the tests. Would probably make them faster as well (no internet round-trips). Refs:

* [moto](https://github.com/spulec/moto)
* [moto for pytest](https://pypi.python.org/pypi/pytest-moto)
* [moto and boto3](https://github.com/spulec/moto/issues/348)

Blockers:

[x] spulec/moto#606
[ ] gabrielfalcao/HTTPretty#247
[ ] gabrielfalcao/HTTPretty#271

**Comment by audax** [comment]
I'd like a switch to run the test against the real server, if needed. Moto should be the default.

**Comment by jmt85** [comment]
please estimate the issue in relation your other issues
