### ISSUE TITLE
extend blockserver to send content length

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-block#6]
for displaying progress in app, send content length of stream

**Comment by audax** [comment]
Implemented, but not yet deployed

**Comment by julianseeger** [comment]
Doesn't the DM contain all filesizes?
Don't know if there are android related problems but for the desktop-client, it works fine even without content length.

**Comment by audax** [comment]
The DM contains the filesize of the unencrypted files which differs by a few bytes. Indeed, that should be accurate enough.The progress bar however is updated in the TransferManager which has no knowledge of the DM. Sending a content length just allows a reuse of the already existing code based on the AWS SDK.

**Comment by audax** [comment]
Implemented
